language: python
python: 2.7
env:
  global:
    PIP_INDEX_URL=https://storax.github.io/travis-pyside-test/simple/
    PIP_EXTRA_INDEX_URL=https://pypi.python.org/simple
    LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
  matrix:
    - TOXENV=check
    - TOXENV=2.7,coveralls
    - TOXENV=2.7-nocover
    - TOXENV=3.3,coveralls
    - TOXENV=3.3-nocover
    - TOXENV=3.4,coveralls
    - TOXENV=3.4-nocover
before_install:
  - python --version
  - virtualenv --version
  - pip --version
  - uname -a
  - lsb_release -a
install:
  - sudo apt-get install xvfb
  - pip install tox
script:
  - Xvfb :0 -screen 0 1600x1200x24 &
  - export DISPLAY=:0.0
  - tox -v
notifications:
  email:
    on_success: never
    on_failure: never
deploy:
  provider: pypi
  user: storax
  distributions: "sdist bdist_wheel"
  password:
    secure: GPvB4YNy+M5KecQDFTPjW2d7QNSAOQ+a7Ck4sRibAn3PARiGdysczoRY7mTk36OdaUVIjWf7C0xgPfA4BK0s82yP3t9iIPlrMnSYQLRoRQ2mIwntgk/qPh4+FeOFTrlWEAllQsACFgooiUmAiMlh4vkos8mueBymB2oJWGKlWgg=
  on:
    tags: true
    repo: Pytwitcher/pytwitcher